import Link from "next/link";
import { ArrowLeft, Check, Clapperboard, Sparkles } from "lucide-react";
import { CheckoutButton } from "@/components/checkout-button";

const free = ["Manual trim and crop", "9:16 preview and captions", "Browser MP4 export", "No watermark", "Your footage stays local"];
const paid = ["Everything in Free", "AI highlight and hook detection", "Three editable Reel concepts", "Dead-air and filler removal", "Word-timed captions", "60 source minutes each month", "1080p cloud rendering"];

export default function PricingPage() {
  const billingEnabled = process.env.NEXT_PUBLIC_BILLING_ENABLED === "true";
  return <main className="min-h-screen overflow-hidden bg-ink px-6 py-8 text-white"><div className="pointer-events-none fixed left-1/2 top-0 h-96 w-[700px] -translate-x-1/2 rounded-full bg-violet/15 blur-[130px]"/><div className="relative mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3 font-extrabold"><span className="brand-mark"><Clapperboard size={17}/></span>FramePilot</Link><Link href="/studio" className="flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={15}/> Back to editor</Link></header><section className="mx-auto max-w-3xl pb-16 pt-24 text-center"><div className="eyebrow mx-auto mb-5 w-fit"><Sparkles size={13}/> Simple plans</div><h1 className="font-display text-5xl font-semibold tracking-[-0.06em] sm:text-7xl">Edit free. Add <span className="text-gradient">AI speed.</span></h1><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-white/50">Normal editing costs nothing. Creator AI is being prepared for the first paid beta.</p></section><section className="mx-auto grid max-w-4xl gap-5 pb-20 md:grid-cols-2"><Plan name="Free editor" price="₹0" note="forever" features={free}><Link href="/studio" className="button-secondary h-12 w-full text-sm">Open free editor</Link></Plan><Plan featured name="Creator AI" price={billingEnabled?"₹999":"Soon"} note={billingEnabled?"per month · cancel anytime":"paid beta"} features={paid}>{billingEnabled?<CheckoutButton/>:<div className="flex h-12 items-center justify-center rounded-full border border-violet/35 bg-violet/10 text-sm font-bold text-violet-200">Paid beta opening soon</div>}</Plan></section>{billingEnabled&&<p className="pb-8 text-center text-xs text-white/25">Payments are processed securely by Razorpay. Prices exclude applicable taxes.</p>}</div></main>;
}

function Plan({name,price,note,features,featured,children}:{name:string;price:string;note:string;features:string[];featured?:boolean;children:React.ReactNode}) { return <article className={`relative rounded-[28px] border p-7 sm:p-9 ${featured?"border-violet/60 bg-violet/[.09] shadow-2xl shadow-violet/10":"border-white/10 bg-white/[.025]"}`}>{featured&&<span className="absolute right-5 top-5 rounded-full bg-lime px-3 py-1 text-[10px] font-black uppercase tracking-wider text-black">Most useful</span>}<h2 className="text-lg font-bold">{name}</h2><div className="mt-8 flex items-end gap-2"><strong className="font-display text-5xl tracking-[-.06em]">{price}</strong><span className="pb-1 text-xs text-white/35">{note}</span></div><ul className="my-8 space-y-3">{features.map(feature=><li key={feature} className="flex items-center gap-3 text-sm text-white/60"><span className={`grid h-5 w-5 place-items-center rounded-full ${featured?"bg-lime text-black":"bg-white/10 text-white"}`}><Check size={12}/></span>{feature}</li>)}</ul>{children}</article>; }
